name: Download ANEEL Excel

on:
  workflow_dispatch:  # 手动触发

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
      - name: Download Resultado_leiloes_transmissao.xlsx
        run: |
          curl -L "https://git.aneel.gov.br/publico/centralconteudo/-/raw/main/relatorioseindicadores/leiloes/Resultado_leiloes_transmissao.xlsx" \
               -o Resultado_leiloes_transmissao.xlsx

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: aneel-resultado-leiloes-transmissao
          path: Resultado_leiloes_transmissao.xlsx
